In [1]:
import numpy as np
np.random.seed(111)
np.random.sample((3,4))

array([[0.61217018, 0.16906975, 0.43605902, 0.76926247],
       [0.2953253 , 0.14916296, 0.02247832, 0.42022449],
       [0.23868214, 0.33765619, 0.99071246, 0.23772645]])

In [2]:
np.random.randint(10,100,(2,3))


array([[82, 47, 86],
       [68, 22, 55]], dtype=int32)

In [3]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [5]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
# linearly spaced values
arr=np.linspace(10,20,5)

In [12]:
#  indexing in numpy
arrys=np.random.randint(10,100,size=(4,5))

In [13]:
arrys[:,:]

array([[71, 55, 58, 44, 71],
       [51, 42, 92, 17, 15],
       [30, 17, 13, 56, 58],
       [44, 38, 92, 82, 87]], dtype=int32)

In [16]:
arrys[[0,3],:]

array([[71, 55, 58, 44, 71],
       [44, 38, 92, 82, 87]], dtype=int32)

In [ ]:
arrys[[0,3],:]